### PR TITLE
add cookie name prefix in config

### PR DESCRIPTION
**Pull request by mamico**
This would permit, for example, to have different consent for sites o subsites where they are in the same 2nd level.

### CODE REVIEW

**Comment by vielhuber** [comment]
Thanks for this helpful and reasonable input.
Could you also please document the usage section in `README.md`
with the new config parameter (perhaps with a short explanation in the form of a comment)?

**Comment by vielhuber** [comment]
I've added the cookie prefix in the readme and streamlined the option (default value is now `cc_`).
Check out release `2.3.5`.
Thanks for your input!

**Comment by mamico** [comment]
> I've added the cookie prefix in the readme and streamlined the option (default value is now `cc_`). Check out release `2.3.5`. Thanks for your input!

@vielhuber thank you and sorry for my silence. I'm currently having some really busy weeks. Probably in the next few days I will submit other PRs. Just a tip: IMO it might be useful to have a change log file to document improvements and fixes over the releases.

**Comment by vielhuber** [comment]
@mamico: Thanks for your input, I will consider that. Looking forward from hearing you!

**Pull request merged**
